name: Spell Check
on: [pull_request, push]

jobs:
  spell_check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - run: pip install codespell
      - run: codespell